name: Run soushuba qiandao
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SOUSHUBA_HOSTNAME: 123.comteslamod123.com
      SOUSHUBA_USERNAME: 3578963
      SOUSHUBA_PASSWORD: 3578963qaz

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python soushuba.py
